line.bot:
  channel-token: {channel-token}
  channel-secret: {channel-secret}
  handler.path: {handler.path}

spring.jpa:
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
  hibernate:
    ddl-auto: update

  #Mysql 설정
spring.datasource:
  url: jdbc:mysql://localhost:3306/{database}?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
  username: {username}
  password: {password}