line.bot:
  channel-token: {channel-token}
  channel-secret: {channel-secret}
  handler.path: {handler.path}

spring.jpa:
  #  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# data 소스 설정
spring.datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password: password
# 테스트 DB h2 설정
spring.h2.console:
  enabled: true
  path: /h2-console